DROP TABLE Tags CASCADE CONSTRAINTS;
DROP TRIGGER PhotoAdded;
DROP SEQUENCE PhotoAdd;
DROP TABLE Photos CASCADE CONSTRAINTS;
DROP TRIGGER AlbumAdded;
DROP SEQUENCE AlbumAdd;
DROP TABLE Albums CASCADE CONSTRAINTS;
DROP TABLE Participants CASCADE CONSTRAINTS;
DROP TRIGGER EventAdded;
DROP SEQUENCE EventAdd;
DROP TABLE User_Events CASCADE CONSTRAINTS;
DROP TABLE Education CASCADE CONSTRAINTS;
DROP TRIGGER ProgramAdded;
DROP SEQUENCE ProgramAdd;
DROP TABLE Programs CASCADE CONSTRAINTS;
DROP TABLE Messages CASCADE CONSTRAINTS;
DROP TABLE User_Hometown_Cities CASCADE CONSTRAINTS;
DROP TABLE User_Current_Cities CASCADE CONSTRAINTS;
DROP TRIGGER CityAdded;
DROP SEQUENCE CityAdd;
DROP TABLE Cities CASCADE CONSTRAINTS;
DROP TRIGGER Order_Friend_Pairs;
DROP TABLE Friends CASCADE CONSTRAINTS;
DROP TRIGGER UserAdded;
DROP SEQUENCE UserAdd;
DROP TABLE Users CASCADE CONSTRAINTS;










